apiVersion: v2
name: metallb
description: MetalLB - bare metal load balancer for Kubernetes
type: application
version: 1.0.0
dependencies:
  - name: metallb
    version: "0.14.9"
    repository: https://metallb.github.io/metallb
