apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ipAddressPools:
    - default-pool
